apiVersion: v1
kind: Service
metadata:
  name: nodejs-fullstack
  namespace: default
  labels:
    k8s-app: nodejs-fullstack
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "nodejs-fullstack"
spec:
  selector:
    k8s-app: nodejs-fullstack
  ports:
  - name: http
    port: 80
    protocol: TCP
  externalIPs:
  - $EXT_IP1
    
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-fullstack
  namespace: default
  labels:
    k8s-app: nodejs-fullstack
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3 
  selector:
    k8s-app: nodejs-fullstack
    version: v1
  template:
    metadata:
      labels:
        k8s-app: nodejs-fullstack
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: nodejs-fullstack
        image: nabadger/nodejs-app
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
        - name: DB_HOST
          value:  "cockroachdb-public"
        - name: DB_PORT
          value: "26257"
        - name: DB_NAME
          value: "test"
        - name: DB_USER
          value: "test"
        - name: DB_PASSWD
          value: ""
