apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld
  namespace: default
  labels:
    k8s-app: nodejs-helloworld
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "nodejs-helloworld"
spec:
  selector:
    k8s-app: nodejs-helloworld
  ports:
  - name: http
    port: 80
    protocol: TCP
  externalIPs:
  - $EXT_IP1
    
---

apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-helloworld
  namespace: default
  labels:
    k8s-app: nodejs-helloworld
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: nodejs-helloworld
    version: v1
  template:
    metadata:
      labels:
        k8s-app: nodejs-helloworld
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: nodejs-helloworld
        image: nabadger/nodejs-helloworld
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 5

